### ISSUE TITLE
The markup filter for money is not callable

### ISSUE THREAD

**Issue by pvullioud** [OFFLINE-GmbH/oc-mall-theme#1]
After a fresh install of oc-mall and oc-mall-them, I have an exception

```
An exception has been thrown during the compilation of a template ("The markup filter for money is not callable.").
....\oc-cv/themes/mall/pages/index.htm line 7
```
Thanks for a direction to fix it

**Comment by tobias-kuendig** [comment]
How did you install the plugin?

It looks like the `helpers.php` is not included via [composer.json](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/composer.json#L10) and there fore the [`format_money`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/7f597fad68ac8d6454ef1b233436bce843605b2c/helpers.php#L26) helper is not available.

I'll try to reproduce the issue with a fresh installation.

**Comment by pvullioud** [comment]
Thanks for your reply.
I cloned both repo with git

**Comment by tobias-kuendig** [comment]
I am unable to reproduce the issue. Have you tried running `composer dump-autoload` to make sure the `helpers.php` file is included correctly? Maybe add a `dd()` statement in the `helpers.php` to check if it is loaded correctly.

I have used to following [`oc-bootstrapper`](https://github.com/OFFLINE-GmbH/oc-bootstrapper/) config to setup the project and everything is working as expected (make sure to create the `malltest` database first):

```yml
app:
    url: http://malltest.test
    locale: de
    debug: true

cms:
    theme: mall (https://github.com/OFFLINE-GmbH/oc-mall-theme.git)
    edgeUpdates: false
    enableSafeMode: false

database:
    connection: mysql
    host: localhost
    port: 3306
    username: root
    password: 
    database: malltest

git:
    deployment: gitlab
    bareRepo: true     

plugins:
    - Rainlab.Pages
    - Rainlab.Sitemap
    - Rainlab.User
    - Rainlab.Location
    - OFFLINE.Mall (https://github.com/OFFLINE-GmbH/oc-mall-plugin.git#develop)

mail:
    host: smtp.mailgun.org
    name: User Name
    address: email@example.com
    driver: log
```
